/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.eventmanagement;

import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Ahsan
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booktable = new javax.swing.JTable();
        deletebook = new javax.swing.JButton();
        printbook = new javax.swing.JButton();
        updatebook = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        displaybook = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        logout2 = new javax.swing.JButton();
        deleteuser = new javax.swing.JButton();
        exit2 = new javax.swing.JButton();
        displayuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jTabbedPane1.setBackground(new java.awt.Color(153, 0, 204));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));

        booktable.setBackground(new java.awt.Color(153, 153, 255));
        booktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Event Type", "Number of Persons", "Food Package", "Time Period", "Event Place"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        booktable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(booktable);

        deletebook.setBackground(new java.awt.Color(153, 51, 255));
        deletebook.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        deletebook.setForeground(new java.awt.Color(255, 255, 255));
        deletebook.setText("Delete");
        deletebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebookActionPerformed(evt);
            }
        });

        printbook.setBackground(new java.awt.Color(153, 51, 255));
        printbook.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        printbook.setForeground(new java.awt.Color(255, 255, 255));
        printbook.setText("Print");
        printbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbookActionPerformed(evt);
            }
        });

        updatebook.setBackground(new java.awt.Color(153, 51, 255));
        updatebook.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        updatebook.setForeground(new java.awt.Color(255, 255, 255));
        updatebook.setText("Update");
        updatebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updatebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebookActionPerformed(evt);
            }
        });

        exit1.setBackground(new java.awt.Color(153, 153, 255));
        exit1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        exit1.setText("Exit");
        exit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });

        logout1.setBackground(new java.awt.Color(153, 153, 255));
        logout1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        logout1.setText("Logout");
        logout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        displaybook.setBackground(new java.awt.Color(153, 51, 255));
        displaybook.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        displaybook.setForeground(new java.awt.Color(255, 255, 255));
        displaybook.setText("Display");
        displaybook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displaybook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletebook, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printbook, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebook, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displaybook, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(deletebook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(printbook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(displaybook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(updatebook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Manage Event Bookings", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 0, 255));

        usertable.setBackground(new java.awt.Color(153, 153, 255));
        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(usertable);

        logout2.setBackground(new java.awt.Color(153, 51, 255));
        logout2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        logout2.setForeground(new java.awt.Color(255, 255, 255));
        logout2.setText("Logout");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });

        deleteuser.setBackground(new java.awt.Color(153, 51, 255));
        deleteuser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        deleteuser.setForeground(new java.awt.Color(255, 255, 255));
        deleteuser.setText("Delete");
        deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserActionPerformed(evt);
            }
        });

        exit2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        exit2.setText("Exit");
        exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit2ActionPerformed(evt);
            }
        });

        displayuser.setBackground(new java.awt.Color(153, 51, 255));
        displayuser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        displayuser.setForeground(new java.awt.Color(255, 255, 255));
        displayuser.setText("Display");
        displayuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayuser, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(displayuser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(logout2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Customers", jPanel3);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logged Out Successfully", "My Output", JOptionPane.INFORMATION_MESSAGE);

        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout1ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit1ActionPerformed

    private void exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit2ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logged Out Successfully", "My Output", JOptionPane.INFORMATION_MESSAGE);

        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout2ActionPerformed

    private void printbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbookActionPerformed
        // TODO add your handling code here:
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        Printable printable = booktable.getPrintable(JTable.PrintMode.NORMAL, null, null);
        printerJob.setPrintable(printable);
        boolean doPrint = printerJob.printDialog();
        if (doPrint) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                // Handle the exception
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_printbookActionPerformed

    private void updatebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebookActionPerformed
        // TODO add your handling code here:
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("events.csv"))) {
        DefaultTableModel tableModel = (DefaultTableModel) booktable.getModel();
        int rowCount = tableModel.getRowCount();
        int columnCount = tableModel.getColumnCount();

        // Write the header
        for (int column = 0; column < columnCount; column++) {
            writer.write(tableModel.getColumnName(column));
            if (column < columnCount - 1) {
                writer.write(",");
            }
        }
        writer.newLine();

        // Write the data
        for (int row = 0; row < rowCount; row++) {
            for (int column = 0; column < columnCount; column++) {
                writer.write((String) tableModel.getValueAt(row, column));
                if (column < columnCount - 1) {
                    writer.write(",");
                }
            }
            writer.newLine();
        }

        System.out.println("Changes saved successfully!");
    } catch (IOException e) {
        e.printStackTrace();
    }        
    }//GEN-LAST:event_updatebookActionPerformed

    private void displayuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayuserActionPerformed
        // TODO add your handling code here:
        try (BufferedReader reader = new BufferedReader(new FileReader("customers.csv"))) {
            String line;
            String[] header = reader.readLine().split(",");
            DefaultTableModel tableModel = (DefaultTableModel) usertable.getModel();
            tableModel.setColumnIdentifiers(header);

            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");
                tableModel.addRow(data);
               }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_displayuserActionPerformed

    private void displaybookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybookActionPerformed
        // TODO add your handling code here:
        try (BufferedReader reader = new BufferedReader(new FileReader("events.csv"))) {
            String line;
            String[] header = reader.readLine().split(",");
            DefaultTableModel tableModel = (DefaultTableModel) booktable.getModel();
            tableModel.setColumnIdentifiers(header);

            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");
                tableModel.addRow(data);
               }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_displaybookActionPerformed

    private void deletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebookActionPerformed
        // TODO add your handling code here:
        int selectedRow = booktable.getSelectedRow();
        if (selectedRow != -1) {
            deletebookRecordFromFile("events.csv", selectedRow);
            DefaultTableModel tableModel = (DefaultTableModel) booktable.getModel();
            tableModel.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(null, "No row selected.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deletebookActionPerformed

    private void deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserActionPerformed
        // TODO add your handling code here:
        int selectedRow = usertable.getSelectedRow();
        if (selectedRow != -1) {
            deleteuserRecordFromFile("customers.csv", selectedRow);
            DefaultTableModel tableModel = (DefaultTableModel) usertable.getModel();
            tableModel.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(null, "No row selected.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteuserActionPerformed

    
    private void deletebookRecordFromFile(String fileName, int rowIndex) {
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName));
        BufferedWriter writer = new BufferedWriter(new FileWriter("temporarybook.tmp"))) {

        String line;

        int currentRow = 0;
        while ((line = reader.readLine()) != null) {
            if (currentRow != rowIndex) {
               writer.write(line);
               writer.newLine();
            }
            currentRow++;
        }

        writer.close();
        reader.close();

        File originalFile = new File(fileName);
        File tempFile = new File("temporarybook.tmp");
        originalFile.delete();
        tempFile.renameTo(originalFile);

        System.out.println("Record deleted successfully!");
        JOptionPane.showMessageDialog(null, "Record Deleted Successfully!", "Event Booking Table", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void deleteuserRecordFromFile(String fileName, int rowIndex) {
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName));
        BufferedWriter writer = new BufferedWriter(new FileWriter("temporaryuser.tmp"))) {

        String line;

        int currentRow = 0;
        while ((line = reader.readLine()) != null) {
            if (currentRow != rowIndex) {
               writer.write(line);
               writer.newLine();
            }
            currentRow++;
        }

        writer.close();
        reader.close();

        File originalFile = new File(fileName);
        File tempFile = new File("temporaryuser.tmp");
        originalFile.delete();
        tempFile.renameTo(originalFile);

        System.out.println("Record deleted successfully!");
        JOptionPane.showMessageDialog(null, "Record Deleted Successfully!", "Event Booking Table", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booktable;
    private javax.swing.JButton deletebook;
    private javax.swing.JButton deleteuser;
    private javax.swing.JButton displaybook;
    private javax.swing.JButton displayuser;
    private javax.swing.JButton exit1;
    private javax.swing.JButton exit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logout1;
    private javax.swing.JButton logout2;
    private javax.swing.JButton printbook;
    private javax.swing.JButton updatebook;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
